# Generated by Django 5.2 on 2025-04-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnonceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('moteur', models.CharField(max_length=50)),
                ('puissance', models.CharField(max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zone', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='annonces/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
