# Generated by Django 5.1.7 on 2025-05-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_agency_address_customuser_agency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Agence', 'Agence'), ('Client', 'Client'), ('Admin', 'Admin')], max_length=10),
        ),
    ]
